name: Generate Changelog

on:
  push:
    # Trigger the workflow on push to the main branch. Adjust the branch name as needed.
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched to access previous commits

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install required Python packages
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      # Step 4: Identify latest and previous "Bump version" commits
      - name: Get Latest Bump Version Commits
        id: get_commits
        run: |
          # Fetch all commits with messages starting with "Bump version"
          COMMITS=$(git log --grep='^Bump version' --pretty=format:"%H" -n 2)
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT

      # Step 5: Generate diff between the two commits
      - name: Generate Diff
        id: generate_diff
        run: |
          COMMITS=(${{ steps.get_commits.outputs.commits }})
          if [ ${#COMMITS[@]} -lt 2 ]; then
            echo "Not enough 'Bump version' commits to generate a diff."
            echo "diff=" >> $GITHUB_OUTPUT
            exit 0
          fi
          OLD_COMMIT=${COMMITS[1]}
          NEW_COMMIT=${COMMITS[0]}
          git diff $OLD_COMMIT $NEW_COMMIT > changelog_diff.patch
          DIFF_CONTENT=$(<changelog_diff.patch)
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Step 6: Check if diff is available
      - name: Check Diff Availability
        if: steps.generate_diff.outputs.diff != ''
        run: echo "Diff generated successfully."

      # Step 7: Generate Changelog Entry using OpenAI
      - name: Generate Changelog Entry
        id: generate_changelog
        if: steps.generate_diff.outputs.diff != ''
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DIFF="${{ steps.generate_diff.outputs.diff }}"
          python generate_changelog.py "$DIFF" > changelog_entry.md
          # Output the changelog entry as a step output
          echo "::set-output name=entry::$(cat changelog_entry.md)"

      # Step 8: Append Changelog Entry to CHANGELOG.md
      - name: Append to Changelog
        if: steps.generate_diff.outputs.diff != ''
        run: |
          echo "## $(date +'%Y-%m-%d')" >> CHANGELOG.md
          cat changelog_entry.md >> CHANGELOG.md
          echo "" >> CHANGELOG.md

      # Step 9: Commit and Push the Updated CHANGELOG.md
      - name: Commit Changelog
        if: steps.generate_diff.outputs.diff != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md"
          git push